// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8nEmjqcNMdSkUbdnU72_g1ZA-D7W4PH0',
    appId: '1:440267938999:web:a959522af62a46b2044132',
    messagingSenderId: '440267938999',
    projectId: 'landpropdb',
    authDomain: 'landpropdb.firebaseapp.com',
    databaseURL: 'https://landpropdb-default-rtdb.firebaseio.com',
    storageBucket: 'landpropdb.firebasestorage.app',
    measurementId: 'G-TF40E6VZ5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlqjEMBoLdRx9_Wctp_3MJ5ucOOCwXVNQ',
    appId: '1:440267938999:android:9e1aa82ed1d447a4044132',
    messagingSenderId: '440267938999',
    projectId: 'landpropdb',
    databaseURL: 'https://landpropdb-default-rtdb.firebaseio.com',
    storageBucket: 'landpropdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4jOWx1rtlydzNiwX4ykp6HLahCqyFH2k',
    appId: '1:440267938999:ios:90e1db44ac7bb9aa044132',
    messagingSenderId: '440267938999',
    projectId: 'landpropdb',
    databaseURL: 'https://landpropdb-default-rtdb.firebaseio.com',
    storageBucket: 'landpropdb.firebasestorage.app',
    iosClientId: '440267938999-rvspafbu2v9pis291lfq3hkf55mk8o6l.apps.googleusercontent.com',
    iosBundleId: 'com.landprop.landpropFe',
  );
}
